extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_SMB1_Ground_layer1_area1_lights;
extern Lights1 bob_dl_SMG2_Grass_layer1_area1_lights;
extern u8 bob_dl_smb1ground_color_rgba16[];
extern u8 bob_dl_smb1ground_value_i4[];
extern u8 bob_dl_smg2grass_ci4[];
extern u8 bob_dl_smg2grass_ci4_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[72];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[42];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_SMB1_Ground_layer1_area1[];
extern Gfx mat_revert_bob_dl_SMB1_Ground_layer1_area1[];
extern Gfx mat_bob_dl_SMG2_Grass_layer1_area1[];
extern Gfx mat_revert_bob_dl_SMG2_Grass_layer1_area1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
